SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCALING = 1.0
SPRITE_SCALING = 0.5

HEALTHBAR_WIDTH = 25
HEALTHBAR_HEIGHT = 3
HEALTHBAR_OFFSET_Y = -10

HEALTH_NUMBER_OFFSET_X = -10
HEALTH_NUMBER_OFFSET_Y = -25